/**
 * AUTO-GENERATED by scripts/build-wallpapers.mjs — do not edit.
 * Drop images into src/client/wallpapers/ and run `npm run bundle`.
 */
export interface Wallpaper {
    id: string;
    name: string;
    dataUrl: string;
}
export declare const WALLPAPERS: Wallpaper[];
//# sourceMappingURL=bg-images.generated.d.ts.map